name             "skeleton"
maintainer       "YOUR NAME"
maintainer_email "YOUR EMAIL"
license          "Apache 2.0"
description      "Installs/configures something"
version          "0.1.0"
recipe           "skeleton::default", "Installs/configures something"
